services:
    database:
        image: mysql:8.0.37
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - ${DB_PORT}:3306
volumes:
    mysql_data:
